package com.android.camera.backup;

import com.android.camera.CameraSettings;
import miui.cloud.backup.data.PrefsBackupHelper;

public class CameraBackupSettings {
    private static final String KEY_ANTIBANDING = "camera_antibanding";
    private static final String KEY_AUTOEXPOSURE = "camera_autoexposure";
    private static final String KEY_AUTO_CHROMA_FLASH = "auto_chroma_flash";
    private static final String KEY_BEAUTIFY_ENLARGE_EYE_RATIO = "beautify_enlarge_eye_ratio";
    private static final String KEY_BEAUTIFY_SKIN_COLOR_RATIO = "beautify_skin_color_ratio";
    private static final String KEY_BEAUTIFY_SKIN_SMOOTH_RATIO = "beautify_skin_smooth_ratio";
    private static final String KEY_BEAUTIFY_SLIM_FACE_RATIO = "beautify_slim_face_ratio";
    private static final String KEY_CAMERA_ASD_NIGHT = "camera_asd_night";
    private static final String KEY_CAMERA_GROUPSHOT_PRIMITIVE = "groupshot_with_primitive_picture";
    private static final String KEY_CAMERA_LYING_TIP_SWITCH = "camera_lying_tip_switch";
    private static final String KEY_CAMERA_PROXIMITY_LOCK = "camera_proximity_lock";
    private static final String KEY_CAMERA_SNAP = "camera_snap";
    private static final String KEY_CAMERA_SOUND = "camerasound";
    private static final String KEY_CAMERA_USER_WATERMARK = "camera_user_watermark";
    private static final String KEY_CAPTURE_WHEN_STABLE = "capture_when_stable";
    private static final String KEY_DUALCAMERA_WATERMARK = "dualcamera_watermark";
    private static final String KEY_FACE_BEAUTY = "camera_face_beauty";
    private static final String KEY_FACE_BEAUTY_SWITCH = "camera_face_beauty_switch";
    private static final String KEY_FACE_DETECTION = "camera_facedetection";
    private static final String KEY_FINGERPRINT_CAPTURE = "fingerprint_capture";
    private static final String KEY_FOCUS_SHOOT = "camera_focus_shoot";
    private static final String KEY_FRONT_MIRROR = "front_mirror";
    private static final String KEY_HEIC_FORMAT = "camera_heic_format";
    private static final String KEY_JPEG_QUALITY = "camera_jpegquality";
    private static final String KEY_LONG_PRESS_SHUTTER = "camera_long_press_shutter";
    private static final String KEY_LONG_PRESS_SHUTTER_FEATURE = "camera_long_press_shutter_feature";
    private static final String KEY_MOVIE_SOLID = "camera_movie_solid";
    private static final String KEY_PICTURE_SIZE = "camera_picturesize";
    private static final String KEY_PRIORITY_STORAGE = "priority_storage";
    private static final String KEY_QC_CONTRAST = "qc_camera_contrast";
    private static final String KEY_QC_EXPOSURETIME = "qc_camera_exposuretime";
    private static final String KEY_QC_FOCUS_POSITION = "focus_position";
    private static final String KEY_QC_ISO = "qc_camera_iso";
    private static final String KEY_QC_MANUAL_WHITEBALANCE_VALUE = "qc_manual_whitebalance_k_value";
    private static final String KEY_QC_SATURATION = "qc_camera_saturation";
    private static final String KEY_QC_SHARPNESS = "qc_camera_sharpness";
    private static final String KEY_RECORD_LOCATION = "camera_recordlocation";
    private static final String KEY_REFERENCE_LINE = "camera_referenceline";
    private static final String KEY_RETAIN_CAMERA_MODE = "retain_camera_mode";
    private static final String KEY_SCAN_QRCODE = "scan_qrcode";
    private static final String KEY_TIME_WATERMARK = "watermark";
    private static final String KEY_VERSION = "version";
    private static final String KEY_VIDEO_ENCODER = "video_encoder";
    private static final String KEY_VIDEO_FOCUS_MODE = "video_focusmode";
    private static final String KEY_VIDEO_HIGH_FRAME_RATE = "video_hfr";
    private static final String KEY_VIDEO_TIME_LAPSE_FRAME_INTERVAL = "video_time_lapse_frame_interval";
    private static final String KEY_VOLUME_CAMERA_FUNCTION = "camera_volumekey_function";
    private static final String KEY_VOLUME_LIVE_FUNCTION = "live_volumekey_function";
    private static final String KEY_VOLUME_PRO_VIDEO_FUNCTION = "pro_video_volumekey_function";
    private static final String KEY_VOLUME_VIDEO_FUNCTION = "video_volumekey_function";
    private static final String KEY_WHITE_BALANCE = "camera_whitebalance";
    static final PrefsBackupHelper.PrefEntry[] PREF_ENTRIES = {PrefsBackupHelper.PrefEntry.createIntEntry("version", CameraSettings.KEY_VERSION), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_RECORD_LOCATION, "pref_camera_recordlocation_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_CAMERA_SOUND, "pref_camerasound_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_CAMERA_PROXIMITY_LOCK, "pref_camera_proximity_lock_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_PRIORITY_STORAGE, "pref_priority_storage"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_RETAIN_CAMERA_MODE, "pref_retain_camera_mode_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_CAMERA_SNAP, "pref_camera_snap_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_CAPTURE_WHEN_STABLE, "pref_capture_when_stable_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_TIME_WATERMARK, "pref_time_watermark_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_DUALCAMERA_WATERMARK, "pref_dualcamera_watermark_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_CAMERA_USER_WATERMARK, "user_define_watermark_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_AUTO_CHROMA_FLASH, "pref_auto_chroma_flash_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_REFERENCE_LINE, "pref_camera_referenceline_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_FOCUS_SHOOT, "pref_camera_focus_shoot_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_SCAN_QRCODE, "pref_scan_qrcode_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_CAMERA_ASD_NIGHT, "pref_camera_asd_night_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_CAMERA_GROUPSHOT_PRIMITIVE, CameraSettings.KEY_CAMERA_GROUPSHOT_PRIMITIVE), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_LONG_PRESS_SHUTTER, "pref_camera_long_press_shutter_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_LONG_PRESS_SHUTTER_FEATURE, "pref_camera_long_press_shutter_feature_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_FRONT_MIRROR, "pref_front_mirror_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_JPEG_QUALITY, "pref_camera_jpegquality_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_HEIC_FORMAT, CameraSettings.KEY_HEIC_FORMAT), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_CAMERA_LYING_TIP_SWITCH, "pref_camera_lying_tip_switch_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_MOVIE_SOLID, "pref_camera_movie_solid_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_VIDEO_ENCODER, "pref_video_encoder_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_VIDEO_TIME_LAPSE_FRAME_INTERVAL, "pref_video_time_lapse_frame_interval_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_FACE_DETECTION, "pref_camera_facedetection_key"), PrefsBackupHelper.PrefEntry.createBoolEntry(KEY_FINGERPRINT_CAPTURE, "pref_fingerprint_capture_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_VOLUME_CAMERA_FUNCTION, "pref_camera_volumekey_function_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_VOLUME_VIDEO_FUNCTION, "pref_video_volumekey_function_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_VOLUME_PRO_VIDEO_FUNCTION, CameraSettings.KEY_VOLUME_PRO_VIDEO_FUNCTION), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_VOLUME_LIVE_FUNCTION, "pref_live_volumekey_function_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_ANTIBANDING, "pref_camera_antibanding_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_QC_CONTRAST, "pref_qc_camera_contrast_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_QC_SATURATION, "pref_qc_camera_saturation_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_QC_SHARPNESS, "pref_qc_camera_sharpness_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_WHITE_BALANCE, CameraSettings.KEY_WHITE_BALANCE), PrefsBackupHelper.PrefEntry.createStringEntry("focus_position", CameraSettings.KEY_QC_FOCUS_POSITION), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_QC_EXPOSURETIME, CameraSettings.KEY_QC_EXPOSURETIME), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_QC_ISO, CameraSettings.KEY_QC_ISO), PrefsBackupHelper.PrefEntry.createIntEntry(KEY_QC_MANUAL_WHITEBALANCE_VALUE, "pref_qc_manual_whitebalance_k_value_key"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_FACE_BEAUTY, "pref_beautify_level_key_capture"), PrefsBackupHelper.PrefEntry.createStringEntry(KEY_FACE_BEAUTY_SWITCH, CameraSettings.KEY_FACE_BEAUTY_SWITCH), PrefsBackupHelper.PrefEntry.createIntEntry(KEY_BEAUTIFY_SLIM_FACE_RATIO, "pref_beautify_slim_face_ratio_key"), PrefsBackupHelper.PrefEntry.createIntEntry(KEY_BEAUTIFY_SKIN_SMOOTH_RATIO, "pref_beautify_skin_smooth_ratio_key"), PrefsBackupHelper.PrefEntry.createIntEntry(KEY_BEAUTIFY_SKIN_COLOR_RATIO, "pref_beautify_skin_color_ratio_key"), PrefsBackupHelper.PrefEntry.createIntEntry(KEY_BEAUTIFY_ENLARGE_EYE_RATIO, "pref_beautify_enlarge_eye_ratio_key")};
}
