package com.ss.android.ttve.monitor;

import android.support.v4.util.ArraySet;
import java.util.Set;

public class TEMonitorNewKeys {
    public static final String TE_COMPOSITION_AUDIO_DECODE_MODE = "te_composition_audio_decode_mode";
    public static final String TE_COMPOSITION_AUDIO_DECODE_TIME = "te_composition_audio_decode_time";
    public static final String TE_COMPOSITION_AUDIO_ENCODE_MODE = "te_composition_audio_encode_mode";
    public static final String TE_COMPOSITION_AUDIO_ENCODE_TIME = "te_composition_audio_encode_time";
    public static final String TE_COMPOSITION_BIT_RATE = "te_composition_bit_rate";
    public static final String TE_COMPOSITION_BRUSH_ADD = "te_composition_brush_add";
    public static final String TE_COMPOSITION_EFFECT_ADD = "te_composition_effect_add";
    public static final String TE_COMPOSITION_EFFECT_JSON = "te_composition_effect_json";
    public static final String TE_COMPOSITION_END_WATERMARK_ADD = "te_composition_end_watermark_add";
    public static final String TE_COMPOSITION_ERR_CODE = "te_composition_err_code";
    public static final String TE_COMPOSITION_FILE_DURATION = "te_composition_file_duration";
    public static final String TE_COMPOSITION_FILE_SIZE = "te_composition_file_size";
    public static final String TE_COMPOSITION_FILTER_ID = "te_composition_filter_id";
    public static final String TE_COMPOSITION_FPS = "te_composition_fps";
    public static final String TE_COMPOSITION_INFO_STICKER_ADD = "te_composition_info_sticker_add";
    public static final String TE_COMPOSITION_INFO_STICKER_JSON = "te_composition_info_sticker_json";
    public static final String TE_COMPOSITION_PAGE_MODE = "te_composition_page_mode";
    public static final String TE_COMPOSITION_RESOLUTION = "te_composition_resolution";
    public static final String TE_COMPOSITION_TEXT_ADD = "te_composition_text_add";
    public static final String TE_COMPOSITION_TIME = "te_composition_time";
    public static final String TE_COMPOSITION_TIME_FILTER_TYPE = "te_composition_time_filter_type";
    public static final String TE_COMPOSITION_TRAN_TYPE = "te_composition_tran_type";
    public static final String TE_COMPOSITION_VIDEO_DECODE_MODE = "te_composition_video_decode_mode";
    public static final String TE_COMPOSITION_VIDEO_DECODE_TIME = "te_composition_video_decode_time";
    public static final String TE_COMPOSITION_VIDEO_ENCODE_MODE = "te_composition_video_encode_mode";
    public static final String TE_COMPOSITION_VIDEO_ENCODE_TIME = "te_composition_video_encode_time";
    public static final String TE_COMPOSITION_VIDEO_GOP = "te_composition_video_gop";
    public static final String TE_COMPOSITION_VIDEO_SW_CRF = "te_composition_video_sw_crf";
    public static final String TE_COMPOSITION_VIDEO_SW_MAXRATE = "te_composition_video_sw_maxrate";
    public static final String TE_COMPOSITION_VIDEO_SW_PRESET = "te_composition_video_sw_preset";
    public static final String TE_COMPOSITION_WATERMARK_ADD = "te_composition_watermark_add";
    public static final String TE_EDIT_AUDIO_DECODE_AVERAGE_TIME = "te_edit_audio_decode_average_time";
    public static final String TE_EDIT_AUDIO_DECODE_MODE = "te_edit_audio_decode_mode";
    public static final String TE_EDIT_ERR_CODE = "te_edit_err_code";
    public static final String TE_EDIT_FIRST_FRAME_TIME = "te_edit_first_frame_time";
    public static final String TE_EDIT_IMPORT_GENERATE_THUMBNAIL_TIME = "te_edit_import_generate_thumbnail_time";
    public static final String TE_EDIT_REVERSE_TIME = "te_edit_reverse_time";
    public static final String TE_EDIT_THUMBNAIL_RESOLUTION = "te_edit_thumbnail_resolution";
    public static final String TE_EDIT_VIDEO_DECODE_AVERAGE_TIME = "te_edit_video_decode_average_time";
    public static final String TE_EDIT_VIDEO_DECODE_MODE = "te_edit_video_decode_mode";
    public static final String TE_MEDIACODEC_PROFILE = "te_mediacodec_profile";
    public static final String TE_PREVIEW_CAMERA_RESOLUTION = "te_preview_camera_resolution";
    public static final String TE_PREVIEW_CAMERA_ZOOM = "te_preview_camera_zoom";
    public static final String TE_PREVIEW_FIRST_FRAME_RENDER_TIME = "te_preview_first_frame_render_time";
    public static final String TE_PREVIEW_FIRST_FRAME_SCREEN_TIME = "te_preview_first_frame_screen_time";
    public static final String TE_PREVIEW_PREVIEW2_FRAME_RATE = "te_preview_preview2_frame_rate";
    public static final String TE_PREVIEW_SWITCH_CAMERA_SCREEN_TIME = "te_preview_switch_camera_screen_time";
    public static final String TE_PREVIEW_VIDEO_PREVIEW_RESOLUTION = "te_preview_video_preview_resolution";
    public static final String TE_RECORD_AUDIO_ENCODE_MODE = "te_record_audio_encode_mode";
    public static final String TE_RECORD_BEAUTY_TYPE = "te_record_beauty_type";
    public static final String TE_RECORD_CAMERA_DIRECTION = "te_record_camera_direction";
    public static final String TE_RECORD_CAMERA_FRAME_RATE = "te_record_camera_frame_rate";
    public static final String TE_RECORD_CAMERA_TYPE = "te_record_camera_type";
    public static final String TE_RECORD_CHEEK_INTENSITY = "te_record_cheek_intensity";
    public static final String TE_RECORD_COMPOSE_VID = "te_record_compose_vid";
    public static final String TE_RECORD_ERR_CODE = "te_record_err_code";
    public static final String TE_RECORD_EXPORT_TIME = "te_record_export_time";
    public static final String TE_RECORD_EXTRACT_FRAME_NUM = "te_record_extract_frame_num";
    public static final String TE_RECORD_EYE_INTENSITY = "te_record_eye_intensity";
    public static final String TE_RECORD_FILTER_ID1 = "te_record_filter_id1";
    public static final String TE_RECORD_FILTER_ID2 = "te_record_filter_id2";
    public static final String TE_RECORD_FRAME_RATE = "te_record_frame_rate";
    public static final String TE_RECORD_LAB_ALGORITHM = "te_record_lab_algorithm";
    public static final String TE_RECORD_MEDIACODEC_RATE_CONTROL = "te_record_mediacodec_rate_control";
    public static final String TE_RECORD_RENDER_AVERAGE_TIME = "te_record_render_average_time";
    public static final String TE_RECORD_RESOLUTION = "te_record_resolution";
    public static final String TE_RECORD_SEGMENT_TIME = "te_record_segment_time";
    public static final String TE_RECORD_SMOOTH_INTENSITY = "te_record_smooth_intensity";
    public static final String TE_RECORD_SPEED = "te_record_speed";
    public static final String TE_RECORD_START_TIME = "te_record_start_time";
    public static final String TE_RECORD_STICKER_ID = "te_record_sticker_id";
    public static final String TE_RECORD_STOP_TIME = "te_record_stop_time";
    public static final String TE_RECORD_SWITCH_CAMERA_TIME = "te_record_switch_camera_time";
    public static final String TE_RECORD_TYPE = "te_record_type";
    public static final String TE_RECORD_VIDEO_ENCODE_GOP = "te_record_video_encode_gop";
    public static final String TE_RECORD_VIDEO_ENCODE_MODE = "te_record_video_encode_mode";
    public static final String TE_RECORD_VIDEO_ENCODE_TYPE = "te_record_video_encode_type";
    public static final String TE_RECORD_VIDEO_FRAME_ENCODE_TIME = "te_record_video_frame_encode_time";
    public static final String TE_RECORD_VIDEO_SOFT_ENCODE_ACC_EGLIMGAE = "te_record_video_soft_encode_acc_eglimage";
    public static final String TE_RECORD_VIDEO_USE_EGLIMAGE = "te_record_video_use_eglimage";
    public static final String TE_RECORD_WHITE_INTENSITY = "te_record_white_intensity";
    public static final String TE_SENSOR_TYPE_ACCELEROMETER_EXIST = "te_sensor_type_accelerometer_exist";
    public static final String TE_SENSOR_TYPE_ACCELEROMETER_NAME = "te_sensor_type_accelerometer_name";
    public static final String TE_SENSOR_TYPE_GAME_ROTATION_VECTOR_EXIST = "te_sensor_type_game_rotation_vector_exist";
    public static final String TE_SENSOR_TYPE_GAME_ROTATION_VECTOR_NAME = "te_sensor_type_game_rotation_vector_name";
    public static final String TE_SENSOR_TYPE_GRAVITY_EXIST = "te_sensor_type_gravity_exist";
    public static final String TE_SENSOR_TYPE_GRAVITY_NAME = "te_sensor_type_gravity_name";
    public static final String TE_SENSOR_TYPE_GYROSCOPE_EXIST = "te_sensor_type_gyroscope_exist";
    public static final String TE_SENSOR_TYPE_GYROSCOPE_NAME = "te_sensor_type_gyroscope_name";
    public static final String TE_SENSOR_TYPE_ROTATION_VECTOR_EXIST = "te_sensor_type_rotation_vector_exist";
    public static final String TE_SENSOR_TYPE_ROTATION_VECTOR_NAME = "te_sensor_type_rotation_vector_name";
    public static int TYPE_BOOL = 3;
    public static int TYPE_DOUBLE = 2;
    public static int TYPE_INT = 1;
    public static int TYPE_STRING;
    private static Set<String> sBoolKeys = new ArraySet();
    private static Set<String> sDoubleKeys = new ArraySet();
    private static Set<String> sIntKeys = new ArraySet();
    private static Set<String> sStringKeys = new ArraySet();

    static {
        sIntKeys.add(TE_PREVIEW_FIRST_FRAME_RENDER_TIME);
        sIntKeys.add(TE_RECORD_BEAUTY_TYPE);
        sIntKeys.add(TE_RECORD_LAB_ALGORITHM);
        sIntKeys.add(TE_RECORD_EXTRACT_FRAME_NUM);
        sIntKeys.add(TE_RECORD_VIDEO_ENCODE_GOP);
        sIntKeys.add("te_record_video_encode_mode");
        sIntKeys.add("te_record_audio_encode_mode");
        sIntKeys.add(TE_RECORD_CAMERA_DIRECTION);
        sIntKeys.add("te_record_camera_type");
        sIntKeys.add("te_record_switch_camera_time");
        sIntKeys.add(TE_MEDIACODEC_PROFILE);
        sIntKeys.add(TE_RECORD_MEDIACODEC_RATE_CONTROL);
        sIntKeys.add(TE_RECORD_TYPE);
        sIntKeys.add(TE_RECORD_ERR_CODE);
        sIntKeys.add(TE_EDIT_FIRST_FRAME_TIME);
        sIntKeys.add(TE_EDIT_REVERSE_TIME);
        sIntKeys.add("te_composition_time");
        sIntKeys.add(TE_COMPOSITION_EFFECT_ADD);
        sIntKeys.add(TE_COMPOSITION_INFO_STICKER_ADD);
        sIntKeys.add(TE_COMPOSITION_WATERMARK_ADD);
        sIntKeys.add(TE_COMPOSITION_TIME_FILTER_TYPE);
        sIntKeys.add(TE_COMPOSITION_TEXT_ADD);
        sIntKeys.add(TE_COMPOSITION_BRUSH_ADD);
        sIntKeys.add(TE_COMPOSITION_ERR_CODE);
        sIntKeys.add(TE_EDIT_VIDEO_DECODE_MODE);
        sIntKeys.add(TE_EDIT_AUDIO_DECODE_MODE);
        sIntKeys.add(TE_EDIT_ERR_CODE);
        sIntKeys.add(TE_EDIT_IMPORT_GENERATE_THUMBNAIL_TIME);
        sIntKeys.add(TE_COMPOSITION_END_WATERMARK_ADD);
        sIntKeys.add("te_composition_video_encode_mode");
        sIntKeys.add("te_composition_video_decode_mode");
        sIntKeys.add("te_composition_audio_encode_mode");
        sIntKeys.add("te_composition_audio_decode_mode");
        sIntKeys.add("te_composition_video_sw_crf");
        sIntKeys.add("te_composition_video_sw_maxrate");
        sIntKeys.add("te_composition_video_sw_preset");
        sIntKeys.add("te_composition_video_gop");
        sIntKeys.add(TE_COMPOSITION_TRAN_TYPE);
        sIntKeys.add(TE_RECORD_VIDEO_USE_EGLIMAGE);
        sIntKeys.add("te_composition_page_mode");
        sDoubleKeys.add(TE_RECORD_SEGMENT_TIME);
        sDoubleKeys.add(TE_PREVIEW_PREVIEW2_FRAME_RATE);
        sDoubleKeys.add(TE_PREVIEW_CAMERA_ZOOM);
        sDoubleKeys.add(TE_RECORD_SMOOTH_INTENSITY);
        sDoubleKeys.add(TE_RECORD_WHITE_INTENSITY);
        sDoubleKeys.add(TE_RECORD_EYE_INTENSITY);
        sDoubleKeys.add(TE_RECORD_CHEEK_INTENSITY);
        sDoubleKeys.add("te_record_video_frame_encode_time");
        sDoubleKeys.add("te_record_frame_rate");
        sDoubleKeys.add("te_record_render_average_time");
        sDoubleKeys.add("te_record_camera_frame_rate");
        sDoubleKeys.add(TE_RECORD_SPEED);
        sDoubleKeys.add("te_record_start_time");
        sDoubleKeys.add("te_record_stop_time");
        sDoubleKeys.add("te_composition_fps");
        sDoubleKeys.add("te_composition_bit_rate");
        sDoubleKeys.add("te_composition_file_duration");
        sDoubleKeys.add("te_composition_file_size");
        sDoubleKeys.add(TE_RECORD_EXPORT_TIME);
        sDoubleKeys.add(TE_PREVIEW_FIRST_FRAME_SCREEN_TIME);
        sDoubleKeys.add(TE_PREVIEW_SWITCH_CAMERA_SCREEN_TIME);
        sDoubleKeys.add(TE_EDIT_VIDEO_DECODE_AVERAGE_TIME);
        sDoubleKeys.add(TE_EDIT_AUDIO_DECODE_AVERAGE_TIME);
        sDoubleKeys.add("te_composition_audio_encode_time");
        sDoubleKeys.add("te_composition_video_decode_time");
        sDoubleKeys.add("te_composition_audio_decode_time");
        sDoubleKeys.add("te_composition_video_encode_time");
        sStringKeys.add(TE_RECORD_COMPOSE_VID);
        sStringKeys.add(TE_PREVIEW_VIDEO_PREVIEW_RESOLUTION);
        sStringKeys.add(TE_PREVIEW_CAMERA_RESOLUTION);
        sStringKeys.add(TE_RECORD_FILTER_ID1);
        sStringKeys.add(TE_RECORD_FILTER_ID2);
        sStringKeys.add(TE_RECORD_STICKER_ID);
        sStringKeys.add("te_record_resolution");
        sStringKeys.add("te_record_video_encode_type");
        sStringKeys.add(TE_RECORD_VIDEO_SOFT_ENCODE_ACC_EGLIMGAE);
        sStringKeys.add("te_composition_resolution");
        sStringKeys.add(TE_COMPOSITION_EFFECT_JSON);
        sStringKeys.add(TE_COMPOSITION_INFO_STICKER_JSON);
        sStringKeys.add(TE_COMPOSITION_FILTER_ID);
        sStringKeys.add(TE_EDIT_THUMBNAIL_RESOLUTION);
        sBoolKeys.add(TE_SENSOR_TYPE_GYROSCOPE_EXIST);
        sBoolKeys.add(TE_SENSOR_TYPE_GAME_ROTATION_VECTOR_EXIST);
        sBoolKeys.add(TE_SENSOR_TYPE_ROTATION_VECTOR_EXIST);
        sBoolKeys.add(TE_SENSOR_TYPE_GRAVITY_EXIST);
        sBoolKeys.add(TE_SENSOR_TYPE_ACCELEROMETER_EXIST);
        sStringKeys.add(TE_SENSOR_TYPE_GYROSCOPE_NAME);
        sStringKeys.add(TE_SENSOR_TYPE_GAME_ROTATION_VECTOR_NAME);
        sStringKeys.add(TE_SENSOR_TYPE_ROTATION_VECTOR_NAME);
        sStringKeys.add(TE_SENSOR_TYPE_GRAVITY_NAME);
        sStringKeys.add(TE_SENSOR_TYPE_ACCELEROMETER_NAME);
    }

    public static int getType(String str) {
        return sIntKeys.contains(str) ? TYPE_INT : sDoubleKeys.contains(str) ? TYPE_DOUBLE : sBoolKeys.contains(str) ? TYPE_BOOL : TYPE_STRING;
    }
}
